server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hth_blog?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      # 主键自增策略，以mysql数据库为准
      id-type: auto
oss:
  accessKey: "sTNq8rKyhIK8yu-wwRBoF7BnKqlyIjvsYpKEWytD"
  secretKey: "ts-vlHWJ5aZxqy4QSZNgLaUGxdksg5K8SJxh-O1Y"
  bucket: "hth-blog"